### Why NumPy??
Numpy is faster and uses less memory than lists.

In [1]:
import numpy as np
import time 
import sys
##Numpy Memory usage

# Creating a NumPy array with 100 elements
array = np.arange(100)
# array.itemsize : Size of one element
# array.size : length of array
print("Size of NumPy array: ", array.itemsize * array.itemsize)

# Creating a list with 100 elements
# Now I'll print the size of list
list = range(0, 10)
# Multiplying size of 1 element with length of the list
print("Size of list: ", sys.getsizeof(1)*len(list))

#Numpy arrays consuming less time than list

Size = 100000

# Creating two lists
list1 = range(Size)
list2 = range(Size)

# Creating two NumPy arrays
arr1 = np.arange(Size)
arr2 = np.arange(Size)

# Calculating time for Python list
start = time.time()
result = [(x,y) for x, y in zip(list1, list2)]
          
print("Time for Python List in msec: ", (time.time() - start) * 1000)

# Calculating time for NumPy array
start = time.time()
result = arr1+arr2
print("Time for NumPy array in msec: ", (time.time()- start) * 1000)

print("\nThis means NumPy array is faster than Python List")

#Numpy arrays are more convinient for scientific operations....
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])

# To add two array you can simply do it by
print("ADD a1 and a2 elements : ", a1+a2)
# To sub two array you can simply do it by
print("SUB a1 and a2 elements : ", a1-a2)

# To mul two array you can simply do it by
print("MUL a1 and a2 elements : ", a1*a2)

# Calculating time for NumPy array
start = time.time()
#result = arr1   arr2
print("Time for NumPy array in msec: ", (time.time()- start) * 1000)

Size of NumPy array:  64
Size of list:  280
Time for Python List in msec:  262.7992630004883
Time for NumPy array in msec:  41.45026206970215

This means NumPy array is faster than Python List
ADD a1 and a2 elements :  [5 7 9]
SUB a1 and a2 elements :  [-3 -3 -3]
MUL a1 and a2 elements :  [ 4 10 18]
Time for NumPy array in msec:  0.23174285888671875


### Intro NumPy and Making 1D arrays

In [2]:
a=np.arange(6) #Making a 1D array with Numpy
print(a)

[0 1 2 3 4 5]


In [3]:
a=np.arange(1,20,2)
# np.arange(start, stop, step)
print(a)

[ 1  3  5  7  9 11 13 15 17 19]


In [4]:
list=[1, 2, 3, 4, 5]
# Making an numpy array from list
a = np.array(list)
print(a)

[1 2 3 4 5]


### Multi Dimensional Arrays

In [5]:
b=np.random.randn(2,3)
#2×3 random matrix
print("b=",b)

b= [[ 0.48129363 -0.0405042  -1.98462922]
 [ 0.8036488  -2.14936785  1.08768997]]


In [9]:
b1=np.array([[1,2,3],[3,4,4]])
# NumpY arrays from list
print("b1=",b1)

b1= [[1 2 3]
 [3 4 4]]


In [8]:
b2=[[2,4,6,8],[1,3,5,7]]
b2_array=np.array(b2)
print("b2=",b2_array)

b2= [[2 4 6 8]
 [1 3 5 7]]


In [12]:
b3=[[2,4,6,8],[1,3,5,7,9]]
b3_array=np.array(b3)
print("b3=",b3_array)
#why result shows type as list 🤔

b3= [list([2, 4, 6, 8]) list([1, 3, 5, 7, 9])]
