### NumPy Special Matrices

In [1]:
import numpy as np

#null matrix
a=np.zeros(7)#default type is float
print("a=",a)
a1=np.zeros((3,3))
print("a1=",a1)

a= [0. 0. 0. 0. 0. 0. 0.]
a1= [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [2]:
#zeros_like will make a new matrix with same shape(order) and dtype(data type).
a2_test=[1,2,3,4,5] #here dtype is int
a2=np.zeros_like(a2_test) #a2 will be 1×5 zero matrix with int dtype.
print("a2=",a2)

a2= [0 0 0 0 0]


In [3]:
#Matrix with all elements as 1
b=np.ones(7)
print("b=",b)

b= [1. 1. 1. 1. 1. 1. 1.]


In [4]:
b1=np.ones((3,4))
print("b1=",b1)

b1= [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [5]:
b2_test=[[1,2,3],[4,5,6],[3,4,5]]
b2=np.ones_like(b2_test)
print("b2=",b2)

b2= [[1 1 1]
 [1 1 1]
 [1 1 1]]


In [8]:
#empty and empty_like used for create new arrays by allocating new memory, but do not populate with any values like ones and   zeros
c=np.zeros((3,6))
#initialize 18 elements with zeros: 3×6 matrix
#if c is not initialized with zeros it wll show garbage values
c=np.empty((2,3,3))
#empty((2,3,3)) creates two 3×3 matrices in where each 3×3 matrix stored in new memory location
#if c is initialized with ones what happens???
print("c=",c)

#There is also empty_like try it yourself...

c= [[[nan nan  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]]


In [9]:
### Produce an array of the given shape and dtype with all values set to the indicated “fill value”

d=np.full((3,3),10)
print("d=",d)

d1_test=np.ones((4,4))
d1=np.full_like((d1_test),11)
print("d1=",d1)

d= [[10 10 10]
 [10 10 10]
 [10 10 10]]
d1= [[11. 11. 11. 11.]
 [11. 11. 11. 11.]
 [11. 11. 11. 11.]
 [11. 11. 11. 11.]]


In [10]:
##### Identity matrix
e=np.eye(4)
print("e=",e)

#we can change index of identity matrix as follows
e=np.eye(4,k=1)
print("Index of identity matrix e is changed. i.e., e=\n",e)
## OR
e1=np.identity(4)
print("e1=",e1)

e= [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Index of identity matrix e is changed. i.e., e=
 [[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]
e1= [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
